name: Update data

on:
  schedule:
    - cron: '0 0 * * *' # once a day
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Installing miller
        run: |-
          sudo apt-get install miller

#      - name: Delete previously generated files
#        run: |-
#          rm data/*.{csv,json}
          
      - name: Run script
        run: |
          chmod +x script/download.sh
          script/download.sh
          
      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "[data] update: ${timestamp}" || exit 0
          git push
