name: update

on:
  schedule:
    - cron: '0 0 * * *' # once a day
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
          
      - name: Download data
        run: |
          chmod +x script/download.sh
          script/download.sh

      - uses: r-lib/actions/setup-r@master

      - name: Set-up R. Install R packages
        run: |
          R -e 'install.packages(c("here", "dplyr", "tidyr", "readr"))'
      
      - name: Run R script. Reshape items
        run: Rscript script/reshape.R
    
#      - name: Install miller
#        run: |-
#          sudo apt-get install miller

      - name: Test Install miller
        run: |-
          sudo apt-get install -y libappindicator1 fonts-liberation
          sudo apt-get -f install
          wget http://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
          mkdir -p ~/bin
          cp bin/mlr ~/bin
          cd ~/bin
          chmod +x mlr
          sudo locale-gen it_IT
          sudo locale-gen it_IT.UTF-8
          sudo update-locale
          export PATH=$PATH:~/bin
          export PATH=$PATH:~/.local/bin
      
      - name: Build json
        run: |-
          chmod +x script/convert.sh
          script/convert.sh
          
      - name: Validate data
        uses: frictionlessdata/repository@v2
        
      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add --all -- ':!inquiry.json' ':!report.json'
          timestamp=$(date --iso-8601=seconds)
          git commit -m "[data] update: ${timestamp}" || exit 0
          git push

      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: indecis.it
          owner: indecis-it
          event_type: sample_push
