name: update

on:
  schedule:
    - cron: '0 0 * * *' # once a day
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Download data
        run: |
          chmod +x script/download.sh
          script/download.sh

      - uses: r-lib/actions/setup-r@master

      - name: Set-up R. Install R packages
        run: |
          R -e 'install.packages(c("here", "dplyr", "tidyr", "readr", "jsonlite"))'
      
      - name: Reshape items (R script)
        run: Rscript script/reshape.R

      - name: Install miller
        run: |-
          curl -kL "https://raw.githubusercontent.com/ondata/covid19italia/master/bin/mlr" > mlr
          mkdir -p ~/bin
          mv mlr ~/bin
          cd ~/bin
          chmod +x mlr

      - name: Build json
        run: |-
          export PATH=$PATH:~/bin
          chmod +x script/convert.sh
          script/convert.sh
          
      - name: Validate data
        uses: frictionlessdata/repository@v2
        
      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add --all -- ':!inquiry.json' ':!report.json'
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push

      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: indecis.it
          owner: indecis-it
          event_type: sample_push
