name: Alert parent repository on push
on:
  push:
    branches:
      - main
    paths:
      - data/**
  workflow_dispatch:
  workflow_run:
    workflows: ["frictionless"]
    types:
      - completed

jobs:
  build:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: indecis.it
          owner: indecis-it
          event_type: sample_push
