name: update_test

on:
  # schedule:
  #   - cron: '0 0 * * *' # once a day
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Download data
        run: |
          chmod +x script/download.sh
          script/download.sh

      - uses: r-lib/actions/setup-r@v2

      - name: Set-up R. Install R packages
        run: |
          R -e 'install.packages(c("here", "dplyr", "tidyr", "readr", "jsonlite"))'
      
      - name: Reshape items & Build json (R script)
        run: Rscript script/t_reshape.R
          
      - name: Validate data
        uses: frictionlessdata/repository@v2
        
      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add --all -- ':!inquiry.json' ':!report.json'
          timestamp=$(date --iso-8601=seconds)
          git commit -m "[test] select lists to display #21" || exit 0
          git push

      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: indecis.it
          owner: indecis-it
          event_type: sample_push
